export const ROOT_ROUTE: string = "/";
export const SEMANTIC_TAGS_ROUTE: string = "/HTML/semantic-tags";
export const TABLES_ROUTE:string = "/HTML/tables";
export const HEAD_ROUTE:string = "/HTML/about-head-tag";
export const FORMS_ROUTE:string = "/HTML/forms";
export const SELECTOR_ROUTE:string = "/CSS/selectors"
export const CONTAINERS_ROUTE:string = "/CSS/containers";
export const POSITIONS_ROUTE:string = "/CSS/positions";
export const GRADIENT_ROUTE:string = "/CSS/gradients";
export const BORDER_ROUTE:string = "/CSS/border"
export const BACKGROUND_ROUTE:string = "/CSS/background"
export const OVERFLOW_ROUTE:string = "/CSS/overflow";
export const BLOCK_ROUTE:string = "/CSS/block-model";
export const STRING_ROUTE:string = "/JS/strings"
export const ARRAYS_ROUTE:string = "/JS/arrays"
export const HOOKS_ROUTE:string = "/react/hooks"
export const ABOUT_ROUTES:string = "/react/about"
export const COOKIE_ROUTE:string = "/others/cookie"
